
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prescaledcronjobs.psc.cronprimer.local
spec:
  validation:
    openAPIV3Schema:     
      properties:    
        spec:
           properties:
            cronJob:
              properties:                
                spec:
                  properties:                    
                    jobTemplate:
                      properties:                        
                        spec:
                          properties:   
                            template:
                              properties:                                
                                spec:
                                  properties:
                                    containers:
                                      items:
                                        properties:
                                          resources:
                                            properties:
                                              limits:
                                                additionalProperties:
                                                  oneOf: 
                                                    - type: string
                                                      pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                                                    - type: integer
                                                  type: 
                                              requests:
                                                additionalProperties:
                                                  oneOf: 
                                                    - type: string
                                                      pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                                                    - type: integer  
                                                  type:   
                                                  